name = "show-api"
main = "src/index.ts"
compatibility_date = "2026-03-19"

[vars]
BASE_DOMAIN = "127.dev"

[[r2_buckets]]
binding = "SHOW_FILES"
bucket_name = "show-files"

[[kv_namespaces]]
binding = "SHOW_META"
id = "933acd16aebe4b5fae7695dfce3eabed"

[triggers]
crons = ["0 * * * *"]
